#!/bin/sh
[ "$1" = start ] || exit 0
if [ -f /data/.nkos-full-update/pending ]; then
    /usr/sbin/nkos-update system-confirm >/var/log/nkos-system-update.log 2>&1 &
    exit 0
fi
[ -f /kvmapp/.os-update/system.json ] || exit 0
/kvmapp/.os-update/system-recovery system-confirm >/var/log/nkos-system-update.log 2>&1 &
