cmake_minimum_required(VERSION 3.16)
project(nkos-openvpn3 LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
list(PREPEND CMAKE_MODULE_PATH "${CORE_SOURCE}/cmake")
include(findcoredeps)
add_executable(nkos-openvpn3 main.cpp)
target_include_directories(nkos-openvpn3 PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
target_compile_definitions(nkos-openvpn3 PRIVATE ENABLE_OVPNDCO OPENVPN_VERSION="3.12-dev+87fd40bb58")
add_core_dependencies(nkos-openvpn3)
find_package(PkgConfig REQUIRED)
pkg_check_modules(LIBNL REQUIRED IMPORTED_TARGET libnl-genl-3.0)
target_link_libraries(nkos-openvpn3 PkgConfig::LIBNL)
install(TARGETS nkos-openvpn3 RUNTIME DESTINATION sbin)
