#!/usr/bin/env python3
"""Generate native Rust layout tables using the immutable baseline Go functions.

Go is only a development oracle in ignored work/. No Go runtime is packaged.
"""
import importlib.util,json,os,subprocess
from pathlib import Path
spec=importlib.util.spec_from_file_location('checks',Path(__file__).with_name('check-v3.py'))
checks=importlib.util.module_from_spec(spec);spec.loader.exec_module(checks)
repo=checks.REPO;baseline='a53b25579ab87cc98f85323b4743deb0d4da907b'
source=subprocess.check_output(['git','show',f'{baseline}:server/service/hid/paste.go'],cwd=repo,text=True)
def item(signature):
    start=source.index(signature);end=source.index('\n}',start)+2;return source[start:end]+'\n'
go='package main\nimport("encoding/json";"os";"sort")\n'+item('type Char struct')
for signature in ['func LangueSwitch(', 'func copyMap(', 'var spanishDeadKeyContinuationMap =', 'func applySpanishLayout(', 'var charMap =']:
    go+=item(signature)
go+='''func main(){result:=map[string]any{};for _,lang:=range []string{"","de","fr","es"}{m:=LangueSwitch(charMap,lang);chars:=[]int{};for c:=range m{chars=append(chars,int(c))};sort.Ints(chars);rows:=[]any{};for _,c:=range chars {k:=m[rune(c)];follow:=[]int{};if lang=="es"{if f,ok:=spanishDeadKeyContinuationMap[rune(c)];ok{follow=[]int{f.Modifiers,f.Code}}};rows=append(rows,map[string]any{"rune":c,"key":[]int{k.Modifiers,k.Code},"follow":follow})};result[lang]=rows};json.NewEncoder(os.Stdout).Encode(result)}'''
out=repo/'work/v3/paste-oracle';out.mkdir(parents=True,exist_ok=True)
path=out/'main.go';path.write_text(go);goroot=checks.PLATFORM/'server/goroot'
env=dict(os.environ,GOROOT=str(goroot),CGO_ENABLED='0',GOCACHE=str(out/'cache'),GO111MODULE='off')
subprocess.run([goroot/'bin/gofmt','-w',path],env=env,check=True)
data=json.loads(subprocess.check_output([goroot/'bin/go','run',path],env=env,cwd=out))
native=['// Generated by scripts/refresh-v3-paste-oracle.py from baseline '+baseline+'.', '// Runtime contains these Rust constants only; Go is a development oracle.', 'pub(crate) type Entry = (char, [u8; 2], Option<[u8; 2]>);', 'pub(crate) fn layout(language: &str) -> &\'static [Entry] {', '    match language {', '        "de" => DE, "fr" => FR, "es" => ES, _ => US,', '    }', '}']
for language,name in [('', 'US'),('de','DE'),('fr','FR'),('es','ES')]:
    native+=['static '+name+': &[Entry] = &[']
    for row in data[language]:
        follow='Some('+str(row['follow'])+')' if row['follow'] else 'None'
        native+=['    (\'\\u{'+format(row['rune'],'x')+'}\', '+str(row['key'])+', '+follow+'),']
    native+= ['];']
(repo/'server-rust/src/paste_layout.rs').write_text('\n'.join(native)+'\n')
(repo/'docs/experiments/v3.0/paste-go-oracle.json').write_text(json.dumps({'baseline':baseline,'layouts':data},indent=2)+'\n')
subprocess.run([checks.CARGO, 'fmt'], cwd=checks.CRATE, check=True)
print('Generated native layout tables and actual Go oracle:', {lang:len(rows) for lang,rows in data.items()})
