// Code generated by firmware/cpu/go-crypto-c906/gen_chacha_riscv64.py. DO NOT EDIT.

// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build gc && !purego

// ChaCha20 for the T-Head C906 (SG2002): five blocks per iteration. Four
// blocks are in XTheadVector lanes (VLEN 128, SEW 32, LMUL 1) with one state
// word per vector register; the fifth block is in scalar registers, its
// instructions interleaved with the vector ones.
//
// Vector registers are not preserved across calls, so all vector state is
// set up and consumed within this call, which calls nothing. Assembly
// functions are not asynchronously preempted; the kernel saves vector state
// across context switches and signals.
//
// Go's assembler has no RVV 0.7.1 encodings, so vector instructions are WORDs.
// The generator checks each against GNU as/objdump -march=rv64gc_xtheadvector.

#include "textflag.h"

// func xorKeyStreamC906(dst, src []byte, key *[8]uint32, nonce *[3]uint32, counter *uint32)
TEXT ·xorKeyStreamC906(SB), 0, $320-72
	MOV	dst_base+0(FP), X23
	MOV	src_base+24(FP), X24
	MOV	src_len+32(FP), X25
	MOV	key+48(FP), X28
	MOV	nonce+56(FP), X29
	MOV	counter+64(FP), X21
	MOVWU	(X21), X26
	ADD	$8, X2, X30
	BEQZ	X25, done
loop:
	MOV	$4, X21
	WORD	$0x008afb57	// th.vsetvli s6,s5,e32,m1,d1
	MOV	$0x61707865, X5
	WORD	$0x5e02c057	// th.vmv.v.x v0,t0
	MOV	$0x3320646e, X6
	WORD	$0x5e0340d7	// th.vmv.v.x v1,t1
	MOV	$0x79622d32, X7
	WORD	$0x5e03c157	// th.vmv.v.x v2,t2
	MOV	$0x6b206574, X8
	WORD	$0x5e0441d7	// th.vmv.v.x v3,s0
	MOVWU	0(X28), X9
	WORD	$0x5e04c257	// th.vmv.v.x v4,s1
	MOVWU	4(X28), X10
	WORD	$0x5e0542d7	// th.vmv.v.x v5,a0
	MOVWU	8(X28), X11
	WORD	$0x5e05c357	// th.vmv.v.x v6,a1
	MOVWU	12(X28), X12
	WORD	$0x5e0643d7	// th.vmv.v.x v7,a2
	MOVWU	16(X28), X13
	WORD	$0x5e06c457	// th.vmv.v.x v8,a3
	MOVWU	20(X28), X14
	WORD	$0x5e0744d7	// th.vmv.v.x v9,a4
	MOVWU	24(X28), X15
	WORD	$0x5e07c557	// th.vmv.v.x v10,a5
	MOVWU	28(X28), X16
	WORD	$0x5e0845d7	// th.vmv.v.x v11,a6
	ADDW	$4, X26, X17
	MOVWU	0(X29), X18
	WORD	$0x5e0946d7	// th.vmv.v.x v13,s2
	MOVWU	4(X29), X19
	WORD	$0x5e09c757	// th.vmv.v.x v14,s3
	MOVWU	8(X29), X20
	WORD	$0x5e0a47d7	// th.vmv.v.x v15,s4
	WORD	$0x5a08aa57	// th.vid.v v20
	WORD	$0x034d4a57	// th.vadd.vx v20,v20,s10
	WORD	$0x5e0a0657	// th.vmv.v.v v12,v20
	MOV	$10, X22
round:
	WORD	$0x02020057	// th.vadd.vv v0,v0,v4
	ADDW	X9, X5
	WORD	$0x021280d7	// th.vadd.vv v1,v1,v5
	ADDW	X10, X6
	WORD	$0x02230157	// th.vadd.vv v2,v2,v6
	ADDW	X11, X7
	WORD	$0x023381d7	// th.vadd.vv v3,v3,v7
	ADDW	X12, X8
	WORD	$0x2ec00657	// th.vxor.vv v12,v12,v0
	XOR	X5, X17
	WORD	$0x2ed086d7	// th.vxor.vv v13,v13,v1
	XOR	X6, X18
	WORD	$0x2ee10757	// th.vxor.vv v14,v14,v2
	XOR	X7, X19
	WORD	$0x2ef187d7	// th.vxor.vv v15,v15,v3
	XOR	X8, X20
	WORD	$0x96c83857	// th.vsll.vi v16,v12,16
	SLLIW	$16, X17, X21
	WORD	$0x96d838d7	// th.vsll.vi v17,v13,16
	SRLIW	$16, X17
	WORD	$0x96e83957	// th.vsll.vi v18,v14,16
	OR	X21, X17
	WORD	$0x96f839d7	// th.vsll.vi v19,v15,16
	SLLIW	$16, X18, X21
	WORD	$0xa2c83657	// th.vsrl.vi v12,v12,16
	SRLIW	$16, X18
	WORD	$0xa2d836d7	// th.vsrl.vi v13,v13,16
	OR	X21, X18
	WORD	$0xa2e83757	// th.vsrl.vi v14,v14,16
	SLLIW	$16, X19, X21
	WORD	$0xa2f837d7	// th.vsrl.vi v15,v15,16
	SRLIW	$16, X19
	WORD	$0x2ac80657	// th.vor.vv v12,v12,v16
	OR	X21, X19
	WORD	$0x2ad886d7	// th.vor.vv v13,v13,v17
	SLLIW	$16, X20, X21
	WORD	$0x2ae90757	// th.vor.vv v14,v14,v18
	SRLIW	$16, X20
	WORD	$0x2af987d7	// th.vor.vv v15,v15,v19
	OR	X21, X20
	WORD	$0x02860457	// th.vadd.vv v8,v8,v12
	ADDW	X17, X13
	WORD	$0x029684d7	// th.vadd.vv v9,v9,v13
	ADDW	X18, X14
	WORD	$0x02a70557	// th.vadd.vv v10,v10,v14
	ADDW	X19, X15
	WORD	$0x02b785d7	// th.vadd.vv v11,v11,v15
	ADDW	X20, X16
	WORD	$0x2e440257	// th.vxor.vv v4,v4,v8
	XOR	X13, X9
	WORD	$0x2e5482d7	// th.vxor.vv v5,v5,v9
	XOR	X14, X10
	WORD	$0x2e650357	// th.vxor.vv v6,v6,v10
	XOR	X15, X11
	WORD	$0x2e7583d7	// th.vxor.vv v7,v7,v11
	XOR	X16, X12
	WORD	$0x96463857	// th.vsll.vi v16,v4,12
	SLLIW	$12, X9, X21
	WORD	$0x965638d7	// th.vsll.vi v17,v5,12
	SRLIW	$20, X9
	WORD	$0x96663957	// th.vsll.vi v18,v6,12
	OR	X21, X9
	WORD	$0x967639d7	// th.vsll.vi v19,v7,12
	SLLIW	$12, X10, X21
	WORD	$0xa24a3257	// th.vsrl.vi v4,v4,20
	SRLIW	$20, X10
	WORD	$0xa25a32d7	// th.vsrl.vi v5,v5,20
	OR	X21, X10
	WORD	$0xa26a3357	// th.vsrl.vi v6,v6,20
	SLLIW	$12, X11, X21
	WORD	$0xa27a33d7	// th.vsrl.vi v7,v7,20
	SRLIW	$20, X11
	WORD	$0x2a480257	// th.vor.vv v4,v4,v16
	OR	X21, X11
	WORD	$0x2a5882d7	// th.vor.vv v5,v5,v17
	SLLIW	$12, X12, X21
	WORD	$0x2a690357	// th.vor.vv v6,v6,v18
	SRLIW	$20, X12
	WORD	$0x2a7983d7	// th.vor.vv v7,v7,v19
	OR	X21, X12
	WORD	$0x02020057	// th.vadd.vv v0,v0,v4
	ADDW	X9, X5
	WORD	$0x021280d7	// th.vadd.vv v1,v1,v5
	ADDW	X10, X6
	WORD	$0x02230157	// th.vadd.vv v2,v2,v6
	ADDW	X11, X7
	WORD	$0x023381d7	// th.vadd.vv v3,v3,v7
	ADDW	X12, X8
	WORD	$0x2ec00657	// th.vxor.vv v12,v12,v0
	XOR	X5, X17
	WORD	$0x2ed086d7	// th.vxor.vv v13,v13,v1
	XOR	X6, X18
	WORD	$0x2ee10757	// th.vxor.vv v14,v14,v2
	XOR	X7, X19
	WORD	$0x2ef187d7	// th.vxor.vv v15,v15,v3
	XOR	X8, X20
	WORD	$0x96c43857	// th.vsll.vi v16,v12,8
	SLLIW	$8, X17, X21
	WORD	$0x96d438d7	// th.vsll.vi v17,v13,8
	SRLIW	$24, X17
	WORD	$0x96e43957	// th.vsll.vi v18,v14,8
	OR	X21, X17
	WORD	$0x96f439d7	// th.vsll.vi v19,v15,8
	SLLIW	$8, X18, X21
	WORD	$0xa2cc3657	// th.vsrl.vi v12,v12,24
	SRLIW	$24, X18
	WORD	$0xa2dc36d7	// th.vsrl.vi v13,v13,24
	OR	X21, X18
	WORD	$0xa2ec3757	// th.vsrl.vi v14,v14,24
	SLLIW	$8, X19, X21
	WORD	$0xa2fc37d7	// th.vsrl.vi v15,v15,24
	SRLIW	$24, X19
	WORD	$0x2ac80657	// th.vor.vv v12,v12,v16
	OR	X21, X19
	WORD	$0x2ad886d7	// th.vor.vv v13,v13,v17
	SLLIW	$8, X20, X21
	WORD	$0x2ae90757	// th.vor.vv v14,v14,v18
	SRLIW	$24, X20
	WORD	$0x2af987d7	// th.vor.vv v15,v15,v19
	OR	X21, X20
	WORD	$0x02860457	// th.vadd.vv v8,v8,v12
	ADDW	X17, X13
	WORD	$0x029684d7	// th.vadd.vv v9,v9,v13
	ADDW	X18, X14
	WORD	$0x02a70557	// th.vadd.vv v10,v10,v14
	ADDW	X19, X15
	WORD	$0x02b785d7	// th.vadd.vv v11,v11,v15
	ADDW	X20, X16
	WORD	$0x2e440257	// th.vxor.vv v4,v4,v8
	XOR	X13, X9
	WORD	$0x2e5482d7	// th.vxor.vv v5,v5,v9
	XOR	X14, X10
	WORD	$0x2e650357	// th.vxor.vv v6,v6,v10
	XOR	X15, X11
	WORD	$0x2e7583d7	// th.vxor.vv v7,v7,v11
	XOR	X16, X12
	WORD	$0x9643b857	// th.vsll.vi v16,v4,7
	SLLIW	$7, X9, X21
	WORD	$0x9653b8d7	// th.vsll.vi v17,v5,7
	SRLIW	$25, X9
	WORD	$0x9663b957	// th.vsll.vi v18,v6,7
	OR	X21, X9
	WORD	$0x9673b9d7	// th.vsll.vi v19,v7,7
	SLLIW	$7, X10, X21
	WORD	$0xa24cb257	// th.vsrl.vi v4,v4,25
	SRLIW	$25, X10
	WORD	$0xa25cb2d7	// th.vsrl.vi v5,v5,25
	OR	X21, X10
	WORD	$0xa26cb357	// th.vsrl.vi v6,v6,25
	SLLIW	$7, X11, X21
	WORD	$0xa27cb3d7	// th.vsrl.vi v7,v7,25
	SRLIW	$25, X11
	WORD	$0x2a480257	// th.vor.vv v4,v4,v16
	OR	X21, X11
	WORD	$0x2a5882d7	// th.vor.vv v5,v5,v17
	SLLIW	$7, X12, X21
	WORD	$0x2a690357	// th.vor.vv v6,v6,v18
	SRLIW	$25, X12
	WORD	$0x2a7983d7	// th.vor.vv v7,v7,v19
	OR	X21, X12
	WORD	$0x02028057	// th.vadd.vv v0,v0,v5
	ADDW	X10, X5
	WORD	$0x021300d7	// th.vadd.vv v1,v1,v6
	ADDW	X11, X6
	WORD	$0x02238157	// th.vadd.vv v2,v2,v7
	ADDW	X12, X7
	WORD	$0x023201d7	// th.vadd.vv v3,v3,v4
	ADDW	X9, X8
	WORD	$0x2ef007d7	// th.vxor.vv v15,v15,v0
	XOR	X5, X20
	WORD	$0x2ec08657	// th.vxor.vv v12,v12,v1
	XOR	X6, X17
	WORD	$0x2ed106d7	// th.vxor.vv v13,v13,v2
	XOR	X7, X18
	WORD	$0x2ee18757	// th.vxor.vv v14,v14,v3
	XOR	X8, X19
	WORD	$0x96f83857	// th.vsll.vi v16,v15,16
	SLLIW	$16, X20, X21
	WORD	$0x96c838d7	// th.vsll.vi v17,v12,16
	SRLIW	$16, X20
	WORD	$0x96d83957	// th.vsll.vi v18,v13,16
	OR	X21, X20
	WORD	$0x96e839d7	// th.vsll.vi v19,v14,16
	SLLIW	$16, X17, X21
	WORD	$0xa2f837d7	// th.vsrl.vi v15,v15,16
	SRLIW	$16, X17
	WORD	$0xa2c83657	// th.vsrl.vi v12,v12,16
	OR	X21, X17
	WORD	$0xa2d836d7	// th.vsrl.vi v13,v13,16
	SLLIW	$16, X18, X21
	WORD	$0xa2e83757	// th.vsrl.vi v14,v14,16
	SRLIW	$16, X18
	WORD	$0x2af807d7	// th.vor.vv v15,v15,v16
	OR	X21, X18
	WORD	$0x2ac88657	// th.vor.vv v12,v12,v17
	SLLIW	$16, X19, X21
	WORD	$0x2ad906d7	// th.vor.vv v13,v13,v18
	SRLIW	$16, X19
	WORD	$0x2ae98757	// th.vor.vv v14,v14,v19
	OR	X21, X19
	WORD	$0x02a78557	// th.vadd.vv v10,v10,v15
	ADDW	X20, X15
	WORD	$0x02b605d7	// th.vadd.vv v11,v11,v12
	ADDW	X17, X16
	WORD	$0x02868457	// th.vadd.vv v8,v8,v13
	ADDW	X18, X13
	WORD	$0x029704d7	// th.vadd.vv v9,v9,v14
	ADDW	X19, X14
	WORD	$0x2e5502d7	// th.vxor.vv v5,v5,v10
	XOR	X15, X10
	WORD	$0x2e658357	// th.vxor.vv v6,v6,v11
	XOR	X16, X11
	WORD	$0x2e7403d7	// th.vxor.vv v7,v7,v8
	XOR	X13, X12
	WORD	$0x2e448257	// th.vxor.vv v4,v4,v9
	XOR	X14, X9
	WORD	$0x96563857	// th.vsll.vi v16,v5,12
	SLLIW	$12, X10, X21
	WORD	$0x966638d7	// th.vsll.vi v17,v6,12
	SRLIW	$20, X10
	WORD	$0x96763957	// th.vsll.vi v18,v7,12
	OR	X21, X10
	WORD	$0x964639d7	// th.vsll.vi v19,v4,12
	SLLIW	$12, X11, X21
	WORD	$0xa25a32d7	// th.vsrl.vi v5,v5,20
	SRLIW	$20, X11
	WORD	$0xa26a3357	// th.vsrl.vi v6,v6,20
	OR	X21, X11
	WORD	$0xa27a33d7	// th.vsrl.vi v7,v7,20
	SLLIW	$12, X12, X21
	WORD	$0xa24a3257	// th.vsrl.vi v4,v4,20
	SRLIW	$20, X12
	WORD	$0x2a5802d7	// th.vor.vv v5,v5,v16
	OR	X21, X12
	WORD	$0x2a688357	// th.vor.vv v6,v6,v17
	SLLIW	$12, X9, X21
	WORD	$0x2a7903d7	// th.vor.vv v7,v7,v18
	SRLIW	$20, X9
	WORD	$0x2a498257	// th.vor.vv v4,v4,v19
	OR	X21, X9
	WORD	$0x02028057	// th.vadd.vv v0,v0,v5
	ADDW	X10, X5
	WORD	$0x021300d7	// th.vadd.vv v1,v1,v6
	ADDW	X11, X6
	WORD	$0x02238157	// th.vadd.vv v2,v2,v7
	ADDW	X12, X7
	WORD	$0x023201d7	// th.vadd.vv v3,v3,v4
	ADDW	X9, X8
	WORD	$0x2ef007d7	// th.vxor.vv v15,v15,v0
	XOR	X5, X20
	WORD	$0x2ec08657	// th.vxor.vv v12,v12,v1
	XOR	X6, X17
	WORD	$0x2ed106d7	// th.vxor.vv v13,v13,v2
	XOR	X7, X18
	WORD	$0x2ee18757	// th.vxor.vv v14,v14,v3
	XOR	X8, X19
	WORD	$0x96f43857	// th.vsll.vi v16,v15,8
	SLLIW	$8, X20, X21
	WORD	$0x96c438d7	// th.vsll.vi v17,v12,8
	SRLIW	$24, X20
	WORD	$0x96d43957	// th.vsll.vi v18,v13,8
	OR	X21, X20
	WORD	$0x96e439d7	// th.vsll.vi v19,v14,8
	SLLIW	$8, X17, X21
	WORD	$0xa2fc37d7	// th.vsrl.vi v15,v15,24
	SRLIW	$24, X17
	WORD	$0xa2cc3657	// th.vsrl.vi v12,v12,24
	OR	X21, X17
	WORD	$0xa2dc36d7	// th.vsrl.vi v13,v13,24
	SLLIW	$8, X18, X21
	WORD	$0xa2ec3757	// th.vsrl.vi v14,v14,24
	SRLIW	$24, X18
	WORD	$0x2af807d7	// th.vor.vv v15,v15,v16
	OR	X21, X18
	WORD	$0x2ac88657	// th.vor.vv v12,v12,v17
	SLLIW	$8, X19, X21
	WORD	$0x2ad906d7	// th.vor.vv v13,v13,v18
	SRLIW	$24, X19
	WORD	$0x2ae98757	// th.vor.vv v14,v14,v19
	OR	X21, X19
	WORD	$0x02a78557	// th.vadd.vv v10,v10,v15
	ADDW	X20, X15
	WORD	$0x02b605d7	// th.vadd.vv v11,v11,v12
	ADDW	X17, X16
	WORD	$0x02868457	// th.vadd.vv v8,v8,v13
	ADDW	X18, X13
	WORD	$0x029704d7	// th.vadd.vv v9,v9,v14
	ADDW	X19, X14
	WORD	$0x2e5502d7	// th.vxor.vv v5,v5,v10
	XOR	X15, X10
	WORD	$0x2e658357	// th.vxor.vv v6,v6,v11
	XOR	X16, X11
	WORD	$0x2e7403d7	// th.vxor.vv v7,v7,v8
	XOR	X13, X12
	WORD	$0x2e448257	// th.vxor.vv v4,v4,v9
	XOR	X14, X9
	WORD	$0x9653b857	// th.vsll.vi v16,v5,7
	SLLIW	$7, X10, X21
	WORD	$0x9663b8d7	// th.vsll.vi v17,v6,7
	SRLIW	$25, X10
	WORD	$0x9673b957	// th.vsll.vi v18,v7,7
	OR	X21, X10
	WORD	$0x9643b9d7	// th.vsll.vi v19,v4,7
	SLLIW	$7, X11, X21
	WORD	$0xa25cb2d7	// th.vsrl.vi v5,v5,25
	SRLIW	$25, X11
	WORD	$0xa26cb357	// th.vsrl.vi v6,v6,25
	OR	X21, X11
	WORD	$0xa27cb3d7	// th.vsrl.vi v7,v7,25
	SLLIW	$7, X12, X21
	WORD	$0xa24cb257	// th.vsrl.vi v4,v4,25
	SRLIW	$25, X12
	WORD	$0x2a5802d7	// th.vor.vv v5,v5,v16
	OR	X21, X12
	WORD	$0x2a688357	// th.vor.vv v6,v6,v17
	SLLIW	$7, X9, X21
	WORD	$0x2a7903d7	// th.vor.vv v7,v7,v18
	SRLIW	$25, X9
	WORD	$0x2a498257	// th.vor.vv v4,v4,v19
	OR	X21, X9
	SUB	$1, X22
	BNEZ	X22, round
	MOV	$0x61707865, X21
	WORD	$0x020ac057	// th.vadd.vx v0,v0,s5
	ADDW	X21, X5
	MOV	$0x3320646e, X21
	WORD	$0x021ac0d7	// th.vadd.vx v1,v1,s5
	ADDW	X21, X6
	MOV	$0x79622d32, X21
	WORD	$0x022ac157	// th.vadd.vx v2,v2,s5
	ADDW	X21, X7
	MOV	$0x6b206574, X21
	WORD	$0x023ac1d7	// th.vadd.vx v3,v3,s5
	ADDW	X21, X8
	MOVWU	0(X28), X21
	WORD	$0x024ac257	// th.vadd.vx v4,v4,s5
	ADDW	X21, X9
	MOVWU	4(X28), X21
	WORD	$0x025ac2d7	// th.vadd.vx v5,v5,s5
	ADDW	X21, X10
	MOVWU	8(X28), X21
	WORD	$0x026ac357	// th.vadd.vx v6,v6,s5
	ADDW	X21, X11
	MOVWU	12(X28), X21
	WORD	$0x027ac3d7	// th.vadd.vx v7,v7,s5
	ADDW	X21, X12
	MOVWU	16(X28), X21
	WORD	$0x028ac457	// th.vadd.vx v8,v8,s5
	ADDW	X21, X13
	MOVWU	20(X28), X21
	WORD	$0x029ac4d7	// th.vadd.vx v9,v9,s5
	ADDW	X21, X14
	MOVWU	24(X28), X21
	WORD	$0x02aac557	// th.vadd.vx v10,v10,s5
	ADDW	X21, X15
	MOVWU	28(X28), X21
	WORD	$0x02bac5d7	// th.vadd.vx v11,v11,s5
	ADDW	X21, X16
	ADDW	$4, X26, X21
	WORD	$0x02ca0657	// th.vadd.vv v12,v12,v20
	ADDW	X21, X17
	MOVWU	0(X29), X21
	WORD	$0x02dac6d7	// th.vadd.vx v13,v13,s5
	ADDW	X21, X18
	MOVWU	4(X29), X21
	WORD	$0x02eac757	// th.vadd.vx v14,v14,s5
	ADDW	X21, X19
	MOVWU	8(X29), X21
	WORD	$0x02fac7d7	// th.vadd.vx v15,v15,s5
	ADDW	X21, X20
	MOVW	X5, 256(X30)
	MOVW	X6, 260(X30)
	MOVW	X7, 264(X30)
	MOVW	X8, 268(X30)
	MOVW	X9, 272(X30)
	MOVW	X10, 276(X30)
	MOVW	X11, 280(X30)
	MOVW	X12, 284(X30)
	MOVW	X13, 288(X30)
	MOVW	X14, 292(X30)
	MOVW	X15, 296(X30)
	MOVW	X16, 300(X30)
	MOVW	X17, 304(X30)
	MOVW	X18, 308(X30)
	MOVW	X19, 312(X30)
	MOVW	X20, 316(X30)
	MOV	$64, X22
	WORD	$0xeb6f7027	// th.vssseg8e.v v0,(t5),s6
	ADD	$32, X30, X21
	WORD	$0xeb6af427	// th.vssseg8e.v v8,(s5),s6
	MOV	$320, X5
	MOV	X30, X6
xorloop:
	WORD	$0x0032f3d7	// th.vsetvli t2,t0,e8,m8,d1
	WORD	$0x020c7007	// th.vle.v v0,(s8)
	WORD	$0x02037407	// th.vle.v v8,(t1)
	WORD	$0x2e040057	// th.vxor.vv v0,v0,v8
	WORD	$0x020bf027	// th.vse.v v0,(s7)
	ADD	X7, X24
	ADD	X7, X23
	ADD	X7, X6
	SUB	X7, X5
	BNEZ	X5, xorloop
	ADDW	$5, X26
	SUB	$320, X25
	BNEZ	X25, loop
done:
	MOV	counter+64(FP), X21
	MOVW	X26, (X21)
	RET
